"""update tables for memory places and schedulers

Revision ID: dfff412e3fd0
Revises: cdfecfa6b033
Create Date: 2026-07-03 17:53:10.928198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfff412e3fd0'
down_revision: Union[str, Sequence[str], None] = 'cdfecfa6b033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='유저가 부르는 장소 이름'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='실제 지번/도로명 주소'),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_places_user_id'), 'memory_places', ['user_id'], unique=False)
    op.create_table('archive_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False, comment='원본 사진 URL'),
    sa.Column('mosaic_image_url', sa.String(length=255), nullable=True, comment='모자이크 처리된 사진 URL'),
    sa.Column('taken_year', sa.Integer(), nullable=False, comment='사진 찍힌 연도 (ex: 1998)'),
    sa.Column('mosaic_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='mosaicstatus', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='archivestatus', native_enum=False, length=50), nullable=False),
    sa.Column('reward_type', sa.Enum('POINT', 'COUPON', 'LOCAL_CURRENCY', name='rewardtype', native_enum=False, length=50), nullable=True),
    sa.Column('reward_status', sa.Enum('PENDING', 'ISSUED', name='rewardstatus', native_enum=False, length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='반려 시 관리자가 남기는 사유'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='관리자가 심사한 시간'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_photos_user_id'), 'archive_photos', ['user_id'], unique=False)
    op.add_column('scheduler_places', sa.Column('day_no', sa.Integer(), nullable=False, comment='몇 일차인지 (당일치기는 무조건 1)'))
    op.add_column('scheduler_places', sa.Column('time_slot', sa.Enum('MORNING', 'LUNCH', 'AFTERNOON', 'DINNER', 'NIGHT', name='timeslot', native_enum=False, length=50), nullable=True, comment='시간대 (아침, 점심, 저녁 등)'))
    op.alter_column('scheduler_places', 'visit_order',
               existing_type=sa.INTEGER(),
               comment='해당 일차의 방문 순서',
               existing_nullable=False)
    op.drop_constraint(op.f('scheduler_places_scheduler_id_fkey'), 'scheduler_places', type_='foreignkey')
    op.create_foreign_key(None, 'scheduler_places', 'schedulers', ['scheduler_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scheduler_places', 'recommended_time')
    op.add_column('schedulers', sa.Column('mobility_mode', sa.Enum('WALK', 'CAR', name='mobilitymode', native_enum=False, length=50), nullable=False))
    op.add_column('schedulers', sa.Column('search_radius', sa.Float(), nullable=False, comment='탐색 반경 (단위: km)'))
    op.add_column('schedulers', sa.Column('trip_type', sa.Enum('DAY_TRIP', 'OVERNIGHT', name='triptype', native_enum=False, length=50), nullable=False))
    op.add_column('schedulers', sa.Column('memory_place_id', sa.Integer(), nullable=True))
    op.add_column('schedulers', sa.Column('companion_type', sa.Enum('SOLO', 'COUPLE', 'FAMILY', 'FRIEND', name='companiontype', native_enum=False, length=50), nullable=False))
    op.add_column('schedulers', sa.Column('companion_count', sa.Integer(), nullable=False))
    op.add_column('schedulers', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False, comment='여행 시작 일시'))
    op.add_column('schedulers', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False, comment='여행 종료 일시'))
    op.alter_column('schedulers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_schedulers_user_id'), 'schedulers', ['user_id'], unique=False)
    op.drop_constraint(op.f('schedulers_user_id_fkey'), 'schedulers', type_='foreignkey')
    op.create_foreign_key(None, 'schedulers', 'memory_places', ['memory_place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedulers', type_='foreignkey')
    op.create_foreign_key(op.f('schedulers_user_id_fkey'), 'schedulers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_schedulers_user_id'), table_name='schedulers')
    op.alter_column('schedulers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('schedulers', 'end_datetime')
    op.drop_column('schedulers', 'start_datetime')
    op.drop_column('schedulers', 'companion_count')
    op.drop_column('schedulers', 'companion_type')
    op.drop_column('schedulers', 'memory_place_id')
    op.drop_column('schedulers', 'trip_type')
    op.drop_column('schedulers', 'search_radius')
    op.drop_column('schedulers', 'mobility_mode')
    op.add_column('scheduler_places', sa.Column('recommended_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scheduler_places', type_='foreignkey')
    op.create_foreign_key(op.f('scheduler_places_scheduler_id_fkey'), 'scheduler_places', 'schedulers', ['scheduler_id'], ['id'])
    op.alter_column('scheduler_places', 'visit_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='해당 일차의 방문 순서',
               existing_nullable=False)
    op.drop_column('scheduler_places', 'time_slot')
    op.drop_column('scheduler_places', 'day_no')
    op.drop_index(op.f('ix_archive_photos_user_id'), table_name='archive_photos')
    op.drop_table('archive_photos')
    op.drop_index(op.f('ix_memory_places_user_id'), table_name='memory_places')
    op.drop_table('memory_places')
    # ### end Alembic commands ###
